version: '3.8'

services:
  app:
    build: 
      context: app/
    ports:
      - "8000:5000"
    command: python app.py
    environment:
      - ENV=production
      - MODEL_PATH=/app/models/model.h5
    volumes:
      - ./app:/app
      - ./models:/app/models
    restart: always

